changes to test-pipeline and backend-deploy workfiles #4

diff --git a/.github/workflows/backend-deploy.yml b/.github/workflows/backend-deploy.yml
--- a/.github/workflows/backend-deploy.yml
+++ b/.github/workflows/backend-deploy.yml
@@ -25,8 +25,12 @@ jobs:
           aws-region: us-west-2
 
       - name: Debug AWS credentials
+        if: always()
         run: |
-          aws sts get-caller-identity
+          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
+          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          echo "Testing AWS CLI access..."
+          aws sts get-caller-identity || echo "Failed to authenticate"
 
 
       - name: Package Lambda functions
